### ISSUE TITLE
Which function can be used to set the incident plane wave to be circularly polarized？

### ISSUE THREAD

**Issue by WangL3i** [victorliu/S4#104]
As the title said. How to set Left Circular Polarization and Right Circular Polarization?

**Comment by gevero** [comment]
You have to choose s and p polarization amplitudes with correct magnitude and phase. Just look at the wikipedia [jones calculus](https://en.wikipedia.org/wiki/Jones_calculus) page to figure it out.

**Comment by Johny-Leo** [comment]
It can be done by setting the s- and p- polarization mag. and phase as such:  s- (1+ i * π/2), and p- (1 - i* π/2) . But keep in mind that the whole field intensity and power are the superposition of the two polarizations, not 1 as in a single pol. case any more.
