### ISSUE TITLE
Cannot execute S4 after installation

### ISSUE THREAD

**Issue by niarmi** [victorliu/S4#107]
Hi everyone,

I ran `make` and installed the software with LUA5.2, but after installation when I run the example, it still shows: 
`lua: fig6.lua:6: attempt to index global 'S4' (a nil value)`
`stack traceback:`
`        fig6.lua:6: in main chunk`
`        [C]: in ?`

Can you help me figure out and solve the problem? Thank you!

**Comment by stijncuyvers** [comment]
Hi niarmi,

I ran into the same problem: you should use the custom S4 lua interpreter. When you want to run an example, run a command as follows in the terminal: "/home/username/conda/envs/virtualenv/Stanford_S4tool/S4/build/S4 name_of_examplefile.lua". This fixed it for me. Hope this helps!

**Comment by niarmi** [comment]
> Hi niarmi,
> 
> I ran into the same problem: you should use the custom S4 lua interpreter. When you want to run an example, run a command as follows in the terminal: "/home/username/conda/envs/virtualenv/Stanford_S4tool/S4/build/S4 name_of_examplefile.lua". This fixed it for me. Hope this helps!

This helps! Thank you so much stijncuyvers!
