### ISSUE TITLE
Multi-threaded execution

### ISSUE THREAD

**Issue by gevero** [victorliu/S4#14]
I am running S4 with python interface on an 64 cores opteron box. Independently of the compilation flags I use to build the software (I tried many) S4 always runs on all the available cores, while I would like the option of a serial run. I should I proceed?

Best

Giovanni

**Comment by WangL3i** [comment]
Hello, I also encountered the same problem, have you solved it? Although eight years have passed.

**Comment by gevero** [comment]
Hi Wang

I actually solved this problem a long time ago, and I forgot about this issue. Depending on your environment, you have to set one of the following environment variables:
```
export OPENBLAS_NUM_THREADS=1
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
```
in the shell, and after you can run your code.

Giovanni
