### ISSUE TITLE
Makefile calls for Makefile.common

### ISSUE THREAD

**Issue by soamaven** [victorliu/S4#38]
Makefile calls for Makefile.common which does not exist in the repo. What was intended to be in there? The parts of Makefile.old below the "do not change line" I will guess and report back with results.

**Comment by JamesBurch** [comment]
Hello,

Did you solve this problem?

Cheers, J

**Comment by soamaven** [comment]
Not really a solution, but I just checked-out the commit before the new Makefile scheme was added. The old Makefile worked just fine for me. I will see if I can make the Makefile.common scheme work and put in a PR... I'm not sure @victorliu intended to leave it out or not.

**Comment by soamaven** [comment]
I made PR #39 to resolve this issue. It should compile, but I get a lot of warnings about unsigned int comparisons... It looks like newer code, so the older core should be fine

**Comment by JamesBurch** [comment]
Thanks a ton, I believe I may have successfully compiled now.
