### ISSUE TITLE
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1 when install on ubuntu14

### ISSUE THREAD

**Issue by sundaechen** [victorliu/S4#59]
Hi, I need help for installing S4 as a Python extension on ubuntu14.04 LTS 64-bit system. I got a few errors like this one:
> error: ‘for’ loop initial declarations are only allowed in C99 mode

And it fails with this message:

> error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
make: *** [S4_pyext] Error 1

Does anyone have any comments on how to fix this problem? Thanks a lot.

------------------------------------------------------------------------------------------------------------
The whole output is below:

> mkdir -p ./build
mkdir -p ./build/S4k
mkdir -p ./build/S4r
mkdir -p ./build/modules
g++ -c -O3 -msse3 -msse2 -msse -fPIC -I. -IS4 -IS4/RNP -IS4/kiss_fft -DHAVE_BLAS -DHAVE_LAPACK -DHAVE_LIBPTHREAD -DHAVE_UNISTD_H S4/S4.cpp -o build/S4k/S4.o
g++ -c -O3 -msse3 -msse2 -msse -fPIC -I. -IS4 -IS4/RNP -IS4/kiss_fft -DHAVE_BLAS -DHAVE_LAPACK -DHAVE_LIBPTHREAD -DHAVE_UNISTD_H S4/rcwa.cpp -o build/S4k/rcwa.o
g++ -c -O3 -msse3 -msse2 -msse -fPIC -I. -IS4 -IS4/RNP -IS4/kiss_fft -DHAVE_BLAS -DHAVE_LAPACK -DHAVE_LIBPTHREAD -DHAVE_UNISTD_H S4/fmm/fmm_common.cpp -o build/S4k/fmm_common.o
g++ -c -O3 -msse3 -msse2 -msse -fPIC -I. -IS4 -IS4/RNP -IS4/kiss_fft -DHAVE_BLAS -DHAVE_LAPACK -DHAVE_LIBPTHREAD -DHAVE_UNISTD_H S4/fmm/fmm_FFT.cpp -o build/S4k/fmm_FFT.o
g++ -c -O3 -msse3 -msse2 -msse -fPIC -I. -IS4 -IS4/RNP -IS4/kiss_fft -DHAVE_BLAS -DHAVE_LAPACK -DHAVE_LIBPTHREAD -DHAVE_UNISTD_H S4/fmm/fmm_kottke.cpp -o build/S4k/fmm_kottke.o
g++ -c -O3 -msse3 -msse2 -msse -fPIC -I. -IS4 -IS4/RNP -IS4/kiss_fft -DHAVE_BLAS -DHAVE_LAPACK -DHAVE_LIBPTHREAD -DHAVE_UNISTD_H S4/fmm/fmm_closed.cpp -o build/S4k/fmm_closed.o
g++ -c -O3 -msse3 -msse2 -msse -fPIC -I. -IS4 -IS4/RNP -IS4/kiss_fft -DHAVE_BLAS -DHAVE_LAPACK -DHAVE_LIBPTHREAD -DHAVE_UNISTD_H S4/fmm/fmm_PolBasisNV.cpp -o build/S4k/fmm_PolBasisNV.o
g++ -c -O3 -msse3 -msse2 -msse -fPIC -I. -IS4 -IS4/RNP -IS4/kiss_fft -DHAVE_BLAS -DHAVE_LAPACK -DHAVE_LIBPTHREAD -DHAVE_UNISTD_H S4/fmm/fmm_PolBasisVL.cpp -o build/S4k/fmm_PolBasisVL.o
g++ -c -O3 -msse3 -msse2 -msse -fPIC -I. -IS4 -IS4/RNP -IS4/kiss_fft -DHAVE_BLAS -DHAVE_LAPACK -DHAVE_LIBPTHREAD -DHAVE_UNISTD_H S4/fmm/fmm_PolBasisJones.cpp -o build/S4k/fmm_PolBasisJones.o
g++ -c -O3 -msse3 -msse2 -msse -fPIC -I. -IS4 -IS4/RNP -IS4/kiss_fft -DHAVE_BLAS -DHAVE_LAPACK -DHAVE_LIBPTHREAD -DHAVE_UNISTD_H S4/fmm/fmm_experimental.cpp -o build/S4k/fmm_experimental.o
g++ -c -O3 -msse3 -msse2 -msse -fPIC -I. -IS4 -IS4/RNP -IS4/kiss_fft -DHAVE_BLAS -DHAVE_LAPACK -DHAVE_LIBPTHREAD -DHAVE_UNISTD_H S4/fmm/fft_iface.cpp -o build/S4k/fft_iface.o
gcc -c -O3 -msse3 -msse2 -msse -fPIC -I. -IS4 -IS4/RNP -IS4/kiss_fft -DHAVE_BLAS -DHAVE_LAPACK -DHAVE_LIBPTHREAD -DHAVE_UNISTD_H S4/pattern/pattern.c -o build/S4k/pattern.o
gcc -c -O3 -msse3 -msse2 -msse -fPIC -I. -IS4 -IS4/RNP -IS4/kiss_fft -DHAVE_BLAS -DHAVE_LAPACK -DHAVE_LIBPTHREAD -DHAVE_UNISTD_H S4/pattern/intersection.c -o build/S4k/intersection.o
gcc -c -O3 -msse3 -msse2 -msse -fPIC -I. -IS4 -IS4/RNP -IS4/kiss_fft -DHAVE_BLAS -DHAVE_LAPACK -DHAVE_LIBPTHREAD -DHAVE_UNISTD_H S4/pattern/predicates.c -o build/S4k/predicates.o
gcc -c -O3 -msse3 -msse2 -msse -fPIC -I. -IS4 -IS4/RNP -IS4/kiss_fft -DHAVE_BLAS -DHAVE_LAPACK -DHAVE_LIBPTHREAD -DHAVE_UNISTD_H S4/numalloc.c -o build/S4k/numalloc.o
gcc -c -O3 -msse3 -msse2 -msse -fPIC -I. -IS4 -IS4/RNP -IS4/kiss_fft -DHAVE_BLAS -DHAVE_LAPACK -DHAVE_LIBPTHREAD -DHAVE_UNISTD_H S4/gsel.c -o build/S4k/gsel.o
gcc -c -O3 -msse3 -msse2 -msse -fPIC -I. -IS4 -IS4/RNP -IS4/kiss_fft -DHAVE_BLAS -DHAVE_LAPACK -DHAVE_LIBPTHREAD -DHAVE_UNISTD_H S4/sort.c -o build/S4k/sort.o
gcc -c -O3 -msse3 -msse2 -msse -fPIC -I. -IS4 -IS4/RNP -IS4/kiss_fft -DHAVE_BLAS -DHAVE_LAPACK -DHAVE_LIBPTHREAD -DHAVE_UNISTD_H S4/kiss_fft/kiss_fft.c -o build/S4k/kiss_fft.o
gcc -c -O3 -msse3 -msse2 -msse -fPIC -I. -IS4 -IS4/RNP -IS4/kiss_fft -DHAVE_BLAS -DHAVE_LAPACK -DHAVE_LIBPTHREAD -DHAVE_UNISTD_H S4/kiss_fft/tools/kiss_fftnd.c -o build/S4k/kiss_fftnd.o
gcc -c -O3 -msse3 -msse2 -msse -fPIC -I. -IS4 -IS4/RNP -IS4/kiss_fft -DHAVE_BLAS -DHAVE_LAPACK -DHAVE_LIBPTHREAD -DHAVE_UNISTD_H S4/SpectrumSampler.c -o build/S4k/SpectrumSampler.o
gcc -c -O3 -msse3 -msse2 -msse -fPIC -I. -IS4 -IS4/RNP -IS4/kiss_fft -DHAVE_BLAS -DHAVE_LAPACK -DHAVE_LIBPTHREAD -DHAVE_UNISTD_H S4/cubature.c -o build/S4k/cubature.o
gcc -c -O3 -msse3 -msse2 -msse -fPIC -I. -IS4 -IS4/RNP -IS4/kiss_fft -DHAVE_BLAS -DHAVE_LAPACK -DHAVE_LIBPTHREAD -DHAVE_UNISTD_H S4/Interpolator.c -o build/S4k/Interpolator.o
gcc -c -O3 -msse3 -msse2 -msse -fPIC -I. -IS4 -IS4/RNP -IS4/kiss_fft -DHAVE_BLAS -DHAVE_LAPACK -DHAVE_LIBPTHREAD -DHAVE_UNISTD_H S4/convert.c -o build/S4k/convert.o
ar crvs build/libS4.a ./build/S4k/S4.o ./build/S4k/rcwa.o ./build/S4k/fmm_common.o ./build/S4k/fmm_FFT.o ./build/S4k/fmm_kottke.o ./build/S4k/fmm_closed.o ./build/S4k/fmm_PolBasisNV.o ./build/S4k/fmm_PolBasisVL.o ./build/S4k/fmm_PolBasisJones.o ./build/S4k/fmm_experimental.o ./build/S4k/fft_iface.o ./build/S4k/pattern.o ./build/S4k/intersection.o ./build/S4k/predicates.o ./build/S4k/numalloc.o ./build/S4k/gsel.o ./build/S4k/sort.o ./build/S4k/kiss_fft.o ./build/S4k/kiss_fftnd.o ./build/S4k/SpectrumSampler.o ./build/S4k/cubature.o ./build/S4k/Interpolator.o ./build/S4k/convert.o
a - ./build/S4k/S4.o
a - ./build/S4k/rcwa.o
a - ./build/S4k/fmm_common.o
a - ./build/S4k/fmm_FFT.o
a - ./build/S4k/fmm_kottke.o
a - ./build/S4k/fmm_closed.o
a - ./build/S4k/fmm_PolBasisNV.o
a - ./build/S4k/fmm_PolBasisVL.o
a - ./build/S4k/fmm_PolBasisJones.o
a - ./build/S4k/fmm_experimental.o
a - ./build/S4k/fft_iface.o
a - ./build/S4k/pattern.o
a - ./build/S4k/intersection.o
a - ./build/S4k/predicates.o
a - ./build/S4k/numalloc.o
a - ./build/S4k/gsel.o
a - ./build/S4k/sort.o
a - ./build/S4k/kiss_fft.o
a - ./build/S4k/kiss_fftnd.o
a - ./build/S4k/SpectrumSampler.o
a - ./build/S4k/cubature.o
a - ./build/S4k/Interpolator.o
a - ./build/S4k/convert.o
echo "-lblas -llapack  -lpthread  " > ./build/tmp.txt
sh gensetup.py.sh ./build ./build/libS4.a
python setup.py build
running build
running build_ext
building 'S4' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/S4
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c S4/main_python.c -o build/temp.linux-x86_64-2.7/S4/main_python.o
S4/main_python.c: In function ‘excitation_converter’:
S4/main_python.c:323:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for(int i = 0; i < data->n; i++)
  ^
S4/main_python.c:323:2: note: use option -std=c99 or -std=gnu99 to compile your code
S4/main_python.c: In function ‘interpolator_table_converter’:
S4/main_python.c:502:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for(int i = 0, ld = data->ny + 1; i < data->n; i++)
  ^
S4/main_python.c:523:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for(int j = 0; j < data->ny; j++)
   ^
S4/main_python.c: In function ‘S4Interpolator_Get’:
S4/main_python.c:579:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for(int i = 0; i < ny; i++)
  ^
S4/main_python.c: In function ‘S4Sim_SetMaterial’:
S4/main_python.c:671:4: warning: assignment makes pointer from integer without a cast [enabled by default]
  M = S4_Simulation_GetMaterialByName(self->S, name);
    ^
S4/main_python.c: In function ‘S4Sim_SetLayer’:
S4/main_python.c:741:20: warning: assignment makes integer from pointer without a cast [enabled by default]
    layer->material = strdup(material);
                    ^
S4/main_python.c: In function ‘S4Sim_SetRegionCircle’:
S4/main_python.c:816:10: warning: comparison between pointer and integer [enabled by default]
  if(NULL != layer->copy){
          ^
S4/main_python.c: In function ‘S4Sim_SetRegionEllipse’:
S4/main_python.c:848:10: warning: comparison between pointer and integer [enabled by default]
  if(NULL != layer->copy){
          ^
S4/main_python.c: In function ‘S4Sim_SetRegionRectangle’:
S4/main_python.c:880:10: warning: comparison between pointer and integer [enabled by default]
  if(NULL != layer->copy){
          ^
S4/main_python.c: In function ‘S4Sim_SetRegionPolygon’:
S4/main_python.c:913:10: warning: comparison between pointer and integer [enabled by default]
  if(NULL != layer->copy){
          ^
S4/main_python.c: In function ‘S4SpectrumSampler_GetFrequencies’:
S4/main_python.c:1696:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for(int i = 0; i < nf; i++)
  ^
S4/main_python.c: In function ‘S4SpectrumSampler_SubmitResults’:
S4/main_python.c:1735:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for(int i = 0; i < ny; i++)
  ^
S4/main_python.c: In function ‘S4SpectrumSampler_GetSpectrum’:
S4/main_python.c:1752:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for(int i = 0; i < n; i++)
  ^
S4/main_python.c: In function ‘S4_SolveInParallel’:
S4/main_python.c:1987:14: warning: unused variable ‘layerName’ [-Wunused-variable]
  const char *layerName;
              ^
S4/main_python.c:1986:15: warning: unused variable ‘kwlist’ [-Wunused-variable]
  static char *kwlist[] = {"S4_Layer", "Simulations", NULL};
               ^
S4/main_python.c: At top level:
S4/main_python.c:653:18: warning: ‘S4Sim_ConvertUnits’ defined but not used [-Wunused-function]
 static PyObject *S4Sim_ConvertUnits(S4Sim *self, PyObject *args)
                  ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
make: *** [S4_pyext] Error 1

**Comment by phoebe-p** [comment]
Have a look at #30, adding the extra argument _extra_compile_args = ['-std=c99']_ in gensetup.py.sh should fix your problem.

**Comment by sundaechen** [comment]
That works. However, I run into another problem that Python cannot import S4. I then follow #44 install S4 from this [fork](https://github.com/soamaven/S4).
